#!/bin/sh
echo $1
echo $2
ssh app@159.203.248.23 <<EOF
cd ~/configurations
git reset --hard
git pull
sudo cp -f webserver/apache2.conf /etc/apache2/
sudo sed -i 's/<ServerName>/159.203.248.23/g' /etc/apache2/apache2.conf
sudo service apache2 restart
exit
EOF