#!/bin/sh
# $1 = server name to be populated in apache2.conf
# $2 = domain name to be populated against ServerName in default virtual host in apache2.conf
# $3 = app server name/IP to be populated in virtual host apache2.conf
# $4 = app server port to be populated in virtual host apache2.conf
ssh app@159.203.248.23 <<EOF
cd ~/configurations
git reset --hard
git pull
echo Environment chosen ="$1"
# source the properties
. ./env/$1/config.properties
echo Adding global ServerName in apache2.conf ="$GblServerName"
echo Adding ServerName in virtual host in apache2.conf ="$VHServerName"
echo Adding app server name/ip in apache2.conf ="$AppServerName"
echo Adding app server port in apache2.conf ="$AppServerPort"
sudo cp -f webserver/apache2.conf /etc/apache2/
sudo sed -i 's/<ServerName>/$GblServerName/g' /etc/apache2/apache2.conf
sudo sed -i 's/<VH_DOMAIN_NAME>/$VHServerName/g' /etc/apache2/apache2.conf
sudo sed -i 's/<APP_SERVER_NAME>/$AppServerName/g' /etc/apache2/apache2.conf
sudo sed -i 's/<APP_SERVER_PORT>/$AppServerPort/g' /etc/apache2/apache2.conf
sudo service apache2 restart
exit
EOF